In [10]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
# data file name  /dataAll.csv  /testAll.csv
data_train = pd.read_csv('dataAll.csv')
#data_train.head()
data_train_add = data_train.iloc[:,:30].applymap(lambda x: x+126.23)
train_loc = data_train.iloc[:,30:]
data_train_add.to_csv("./processed_data/train_pro.csv",index = False)
m = data_train_add.describe()
m.to_csv("./processed_data/des_pro.csv",index = False)
train_loc_list=[]
for i in range(len(train_loc)):
    train_loc_list.append([train_loc.iloc[i,0],train_loc.iloc[i,1]])
len(train_loc_list)

a=data_train_add.columns.values.tolist()

m = [i for i in range(0,30,2)]
#m=[0,6,9,11,13,17,19,23,26]
order=[]
for i in m:
    order.extend([a[i]])
reoder_data = data_train_add[order]
reoder_data.to_csv("./processed_data/feature.csv",index = False)
data_train_add = pd.read_csv('./processed_data/feature.csv')


def cos_vali(data_list,class_list,test_size = 0.2):
    data_class_list = list(zip(data_list, class_list))
    import random
    random.shuffle(data_class_list)
    index = int(len(data_class_list)*test_size)#+1
    train_list = data_class_list[index:]
    test_list = data_class_list[:index]
    train_data_list, train_class_list = zip(*train_list)
    test_data_list, test_class_list = zip(*test_list)
    return list(train_data_list),list(test_data_list),list(train_class_list),list(test_class_list)
# Create a random dataset
def error(y_test,y_pre):
    m = y_test-y_pre
    m=np.square(m)
    m=m.sum(axis=1)
    m=np.sqrt(m)
    return m.sum()/len(y_test)

In [11]:
X_train, X_test, y_train, y_test = cos_vali(np.array(data_train_add).tolist(),train_loc_list)
X_train, X_test, y_train, y_test = np.array(X_train),np.array(X_test),np.array(y_train),np.array(y_test)
regr_multirf = MultiOutputRegressor(RandomForestRegressor(n_estimators=100,
                            max_depth=27,min_samples_leaf=2,oob_score=True))
regr_multirf.fit(X_train, y_train)

y_multirf = regr_multirf.predict(X_test)
       
m=error(y_test,y_multirf)
        
print(m)

1.7281715148771395

In [3]:
data_train.head()

,21000,21001,21002,21003,21004,21005,21006,21007,21008,21009,...,35007,35008,35009,350010,350011,350012,350013,350014,x,y
0,-126.23,-126.23,-126.23,-96.28,-126.23,-126.23,-126.23,-126.23,-97.92,-124.68,...,-126.23,-126.23,-106.09,-109.26,-94.31,-101.30,-102.86,-126.23,0.0,10.8
1,-126.23,-126.23,-126.23,-126.23,-126.23,-126.23,-126.23,-105.06,-95.94,-126.23,...,-126.23,-126.23,-104.70,-126.23,-92.16,-100.80,-101.01,-126.23,0.0,11.4
2,-126.23,-126.23,-126.23,-126.23,-126.23,-126.23,-126.23,-126.23,-95.92,-116.21,...,-126.23,-126.23,-104.64,-126.23,-91.62,-100.41,-100.74,-126.23,0.0,12.0
3,-126.23,-126.23,-126.23,-111.22,-126.23,-126.23,-126.23,-126.23,-96.70,-108.96,...,-126.23,-126.23,-104.57,-126.23,-91.27,-99.74,-100.50,-126.23,0.0,12.6
4,-126.23,-126.23,-126.23,-104.29,-126.23,-126.23,-126.23,-126.23,-96.70,-107.75,...,-126.23,-123.01,-104.55,-126.23,-91.09,-99.12,-100.30,-119.82,0.0,13.2

In [7]:
m = [i for i in range(0,30,2)]

In [8]:
m

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [9]:
data_train.iloc[:,28]

0      -102.86
1      -101.01
2      -100.74
3      -100.50
4      -100.30
5      -100.12
6       -99.96
7       -99.82
8       -99.71
9       -99.64
10     -102.34
11     -112.19
12     -100.14
13      -99.70
14      -99.78
15      -99.89
16     -100.04
17     -100.20
18     -100.39
19     -100.60
20     -100.83
21     -101.07
22     -101.32
23     -101.68
24     -103.44
25     -103.81
26     -101.41
27     -100.42
28     -100.16
29      -99.90
         ...
3833   -126.23
3834   -126.23
3835   -126.23
3836   -126.23
3837   -126.23
3838   -126.23
3839   -126.23
3840   -126.23
3841   -126.23
3842   -126.23
3843   -126.23
3844   -126.23
3845   -126.23
3846   -126.23
3847   -126.23
3848   -126.23
3849   -126.23
3850   -126.23
3851   -126.23
3852   -126.23
3853   -126.23
3854   -126.23
3855   -126.23
3856   -126.23
3857   -126.23
3858   -126.23
3859   -126.23
3860   -126.23
3861   -126.23
3862   -126.23
Name: 350013, Length: 3863, dtype: float64